// Auto-generated file - DO NOT EDIT
// Generated by: npm run validate:test-data

/**
 * Valid slugs from mock data for use in tests
 */

export const VALID_TEST_SLUGS = {
  agencies: [
  'industrial-staffing-solutions',
  'tradepower-recruiting',
  'shutdown-specialists-inc',
  'elite-construction-staffing',
  'union-trades-collective',
  'maritime-construction-crew',
  'rocky-mountain-workforce',
  'northeast-industrial-partners',
  'pacific-coast-builders',
  'midwest-manufacturing-staffing',
  'energy-sector-solutions',
  'southeast-infrastructure-group'
],
  
  trades: [
  'millwright',
  'pipefitter',
  'welder',
  'electrician',
  'boilermaker',
  'heavy-equipment-operator',
  'crane-operator',
  'ironworker',
  'carpenter',
  'concrete-finisher',
  'shutdown-crew',
  'scaffold-builder',
  'insulator',
  'plumber',
  'hvac-technician',
  'drywall-installer',
  'journeyman-electrician',
  'journeyman-plumber',
  'union-ironworker',
  'operating-engineer',
  'sheet-metal-worker',
  'marine-welder',
  'underwater-welder',
  'rigger',
  'dive-tender',
  'blaster',
  'mining-equipment-operator',
  'mechanic',
  'instrumentation-technician',
  'maintenance-mechanic',
  'quality-inspector',
  'tower-crane-operator',
  'glazier',
  'roofer',
  'cnc-machinist',
  'maintenance-technician',
  'quality-control-inspector',
  'forklift-operator',
  'production-supervisor',
  'wind-technician',
  'solar-installer',
  'electrical-lineman',
  'substation-technician',
  'pipeline-welder',
  'bridge-builder',
  'surveyor',
  'traffic-control-specialist',
  'asphalt-worker'
],
  
  states: [
  'AL',
  'AK',
  'AZ',
  'AR',
  'CA',
  'CO',
  'CT',
  'DE',
  'FL',
  'GA',
  'HI',
  'ID',
  'IL',
  'IN',
  'IA',
  'KS',
  'KY',
  'LA',
  'ME',
  'MD',
  'MA',
  'MI',
  'MN',
  'MS',
  'MO',
  'MT',
  'NE',
  'NV',
  'NH',
  'NJ',
  'NM',
  'NY',
  'NC',
  'ND',
  'OH',
  'OK',
  'OR',
  'PA',
  'RI',
  'SC',
  'SD',
  'TN',
  'TX',
  'UT',
  'VT',
  'VA',
  'WA',
  'WV',
  'WI',
  'WY'
],
} as const;

// Helper to get a random valid slug for testing
export function getRandomAgencySlug(): string {
  const slugs = VALID_TEST_SLUGS.agencies;
  return slugs[Math.floor(Math.random() * slugs.length)];
}

export function getRandomTradeSlug(): string {
  const slugs = VALID_TEST_SLUGS.trades;
  return slugs[Math.floor(Math.random() * slugs.length)];
}

export function getRandomStateCode(): string {
  const codes = VALID_TEST_SLUGS.states;
  return codes[Math.floor(Math.random() * codes.length)];
}
