// Enhanced mock data for the directory with more realistic agency profiles
export const mockAgencies = [
  {
    name: "Industrial Staffing Solutions",
    website: "https://industrialstaffing.com",
    logo_url: "https://images.pexels.com/photos/1181533/pexels-photo-1181533.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&fit=crop",
    description: "Leading provider of skilled industrial workforce solutions with over 20 years of experience in petrochemical, refinery, and heavy industrial projects. We specialize in turnarounds, shutdowns, and major capital projects across the Gulf Coast.",
    trades: ["Millwright", "Pipefitter", "Welder", "Electrician", "Boilermaker"],
    regions: ["Texas", "Louisiana", "Oklahoma", "Arkansas"],
    offers_per_diem: true,
    is_union: false,
    founded_year: 2003,
    employee_count: "500-1000",
    headquarters: "Houston, TX"
  },
  {
    name: "TradePower Recruiting",
    website: "https://tradepower.com",
    logo_url: "https://images.pexels.com/photos/1181406/pexels-photo-1181406.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&fit=crop",
    description: "Premier construction recruiting firm serving major infrastructure projects nationwide. We connect top-tier skilled trades professionals with leading contractors on high-profile commercial and industrial construction projects.",
    trades: ["Heavy Equipment Operator", "Crane Operator", "Ironworker", "Carpenter", "Concrete Finisher"],
    regions: ["California", "Nevada", "Arizona", "Utah", "Colorado"],
    offers_per_diem: true,
    is_union: true,
    founded_year: 1998,
    employee_count: "200-500",
    headquarters: "Los Angeles, CA"
  },
  {
    name: "Shutdown Specialists Inc",
    website: "https://shutdownspecialists.com",
    logo_url: "https://images.pexels.com/photos/1181772/pexels-photo-1181772.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&fit=crop",
    description: "Expert turnaround and shutdown crews for refineries and chemical plants. Our specialized teams have completed over 500 major turnarounds with zero safety incidents. We maintain a database of pre-screened, certified professionals.",
    trades: ["Shutdown Crew", "Scaffold Builder", "Insulator", "Boilermaker", "Pipefitter"],
    regions: ["Texas", "Louisiana", "Mississippi", "Alabama", "Florida"],
    offers_per_diem: true,
    is_union: false,
    founded_year: 2010,
    employee_count: "100-200",
    headquarters: "Baton Rouge, LA"
  },
  {
    name: "Elite Construction Staffing",
    website: "https://eliteconstructionstaffing.com",
    logo_url: "https://images.pexels.com/photos/1181263/pexels-photo-1181263.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&fit=crop",
    description: "High-quality skilled trades staffing for commercial and residential construction. We focus on long-term placements and career development for construction professionals across the Southeast region.",
    trades: ["Electrician", "Plumber", "HVAC Technician", "Carpenter", "Drywall Installer"],
    regions: ["Florida", "Georgia", "South Carolina", "North Carolina", "Tennessee"],
    offers_per_diem: false,
    is_union: false,
    founded_year: 2015,
    employee_count: "50-100",
    headquarters: "Atlanta, GA"
  },
  {
    name: "Union Trades Collective",
    website: "https://uniontrades.com",
    logo_url: "https://images.pexels.com/photos/1181715/pexels-photo-1181715.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&fit=crop",
    description: "Connecting union contractors with certified journeymen and apprentices across the Midwest. We maintain strong relationships with local unions and provide comprehensive workforce solutions for large-scale projects.",
    trades: ["Journeyman Electrician", "Journeyman Plumber", "Union Ironworker", "Operating Engineer", "Sheet Metal Worker"],
    regions: ["Illinois", "Wisconsin", "Indiana", "Michigan", "Ohio"],
    offers_per_diem: true,
    is_union: true,
    founded_year: 1985,
    employee_count: "1000+",
    headquarters: "Chicago, IL"
  },
  {
    name: "Maritime Construction Crew",
    website: "https://maritimeconstruction.com",
    logo_url: "https://images.pexels.com/photos/1181359/pexels-photo-1181359.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&fit=crop",
    description: "Specialized marine construction and offshore platform staffing. Our crews are certified for underwater welding, marine construction, and offshore oil & gas projects with extensive safety training and certifications.",
    trades: ["Marine Welder", "Underwater Welder", "Rigger", "Crane Operator", "Dive Tender"],
    regions: ["Louisiana", "Texas", "Mississippi", "Alabama", "Florida"],
    offers_per_diem: true,
    is_union: false,
    founded_year: 2008,
    employee_count: "100-200",
    headquarters: "New Orleans, LA"
  },
  {
    name: "Rocky Mountain Workforce",
    website: "https://rockymountainworkforce.com",
    logo_url: "https://images.pexels.com/photos/1181677/pexels-photo-1181677.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&fit=crop",
    description: "Premier staffing solutions for mining, energy, and heavy construction projects across the Rocky Mountain region. We specialize in high-altitude and extreme weather construction projects.",
    trades: ["Heavy Equipment Operator", "Blaster", "Mining Equipment Operator", "Welder", "Mechanic"],
    regions: ["Colorado", "Wyoming", "Montana", "Utah", "New Mexico"],
    offers_per_diem: true,
    is_union: false,
    founded_year: 2012,
    employee_count: "200-500",
    headquarters: "Denver, CO"
  },
  {
    name: "Northeast Industrial Partners",
    website: "https://northeastindustrial.com",
    logo_url: "https://images.pexels.com/photos/1181467/pexels-photo-1181467.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&fit=crop",
    description: "Comprehensive industrial staffing services for manufacturing, power generation, and infrastructure projects. We maintain a network of skilled professionals across the Northeast corridor.",
    trades: ["Millwright", "Electrician", "Instrumentation Technician", "Maintenance Mechanic", "Quality Inspector"],
    regions: ["New York", "Pennsylvania", "New Jersey", "Connecticut", "Massachusetts"],
    offers_per_diem: false,
    is_union: true,
    founded_year: 1992,
    employee_count: "500-1000",
    headquarters: "Newark, NJ"
  },
  {
    name: "Pacific Coast Builders",
    website: "https://pacificcoastbuilders.com",
    logo_url: "https://images.pexels.com/photos/1181396/pexels-photo-1181396.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&fit=crop",
    description: "Leading construction staffing agency serving the West Coast with expertise in high-rise construction, infrastructure projects, and green building initiatives. We focus on sustainable construction practices.",
    trades: ["Tower Crane Operator", "Ironworker", "Concrete Finisher", "Glazier", "Roofer"],
    regions: ["California", "Oregon", "Washington", "Nevada"],
    offers_per_diem: true,
    is_union: true,
    founded_year: 2005,
    employee_count: "200-500",
    headquarters: "San Francisco, CA"
  },
  {
    name: "Midwest Manufacturing Staffing",
    website: "https://midwestmanufacturing.com",
    logo_url: "https://images.pexels.com/photos/1181562/pexels-photo-1181562.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&fit=crop",
    description: "Specialized staffing for manufacturing and industrial facilities across the Midwest. We provide both temporary and permanent placements for skilled manufacturing professionals.",
    trades: ["CNC Machinist", "Maintenance Technician", "Quality Control Inspector", "Forklift Operator", "Production Supervisor"],
    regions: ["Illinois", "Indiana", "Wisconsin", "Iowa", "Missouri"],
    offers_per_diem: false,
    is_union: false,
    founded_year: 2018,
    employee_count: "50-100",
    headquarters: "Milwaukee, WI"
  },
  {
    name: "Energy Sector Solutions",
    website: "https://energysectorsolutions.com",
    logo_url: "https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&fit=crop",
    description: "Specialized workforce solutions for renewable energy, oil & gas, and power generation projects. Our professionals are certified for wind, solar, and traditional energy infrastructure projects.",
    trades: ["Wind Technician", "Solar Installer", "Electrical Lineman", "Substation Technician", "Pipeline Welder"],
    regions: ["Texas", "Oklahoma", "Kansas", "North Dakota", "Wyoming"],
    offers_per_diem: true,
    is_union: false,
    founded_year: 2014,
    employee_count: "100-200",
    headquarters: "Dallas, TX"
  },
  {
    name: "Southeast Infrastructure Group",
    website: "https://southeastinfrastructure.com",
    logo_url: "https://images.pexels.com/photos/1181425/pexels-photo-1181425.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&fit=crop",
    description: "Infrastructure and heavy civil construction staffing across the Southeast. We specialize in highway construction, bridge projects, and major infrastructure developments.",
    trades: ["Heavy Equipment Operator", "Bridge Builder", "Surveyor", "Traffic Control Specialist", "Asphalt Worker"],
    regions: ["Georgia", "Florida", "Alabama", "South Carolina", "North Carolina"],
    offers_per_diem: true,
    is_union: false,
    founded_year: 2007,
    employee_count: "200-500",
    headquarters: "Jacksonville, FL"
  }
];

export const allTrades = [
  "Millwright", "Pipefitter", "Welder", "Electrician", "Heavy Equipment Operator",
  "Crane Operator", "Ironworker", "Carpenter", "Shutdown Crew", "Scaffold Builder",
  "Insulator", "Boilermaker", "Plumber", "HVAC Technician", "Journeyman Electrician",
  "Journeyman Plumber", "Union Ironworker", "Operating Engineer", "Marine Welder",
  "Underwater Welder", "Rigger", "Forklift Operator", "Safety Coordinator",
  "Quality Control Inspector", "Project Manager", "Site Supervisor", "Concrete Finisher",
  "Drywall Installer", "Sheet Metal Worker", "Dive Tender", "Blaster", "Mining Equipment Operator",
  "Mechanic", "Instrumentation Technician", "Maintenance Mechanic", "Tower Crane Operator",
  "Glazier", "Roofer", "CNC Machinist", "Maintenance Technician", "Production Supervisor",
  "Wind Technician", "Solar Installer", "Electrical Lineman", "Substation Technician",
  "Pipeline Welder", "Bridge Builder", "Surveyor", "Traffic Control Specialist", "Asphalt Worker"
];

export const allStates = [
  { name: "Alabama", code: "AL" },
  { name: "Alaska", code: "AK" },
  { name: "Arizona", code: "AZ" },
  { name: "Arkansas", code: "AR" },
  { name: "California", code: "CA" },
  { name: "Colorado", code: "CO" },
  { name: "Connecticut", code: "CT" },
  { name: "Delaware", code: "DE" },
  { name: "Florida", code: "FL" },
  { name: "Georgia", code: "GA" },
  { name: "Hawaii", code: "HI" },
  { name: "Idaho", code: "ID" },
  { name: "Illinois", code: "IL" },
  { name: "Indiana", code: "IN" },
  { name: "Iowa", code: "IA" },
  { name: "Kansas", code: "KS" },
  { name: "Kentucky", code: "KY" },
  { name: "Louisiana", code: "LA" },
  { name: "Maine", code: "ME" },
  { name: "Maryland", code: "MD" },
  { name: "Massachusetts", code: "MA" },
  { name: "Michigan", code: "MI" },
  { name: "Minnesota", code: "MN" },
  { name: "Mississippi", code: "MS" },
  { name: "Missouri", code: "MO" },
  { name: "Montana", code: "MT" },
  { name: "Nebraska", code: "NE" },
  { name: "Nevada", code: "NV" },
  { name: "New Hampshire", code: "NH" },
  { name: "New Jersey", code: "NJ" },
  { name: "New Mexico", code: "NM" },
  { name: "New York", code: "NY" },
  { name: "North Carolina", code: "NC" },
  { name: "North Dakota", code: "ND" },
  { name: "Ohio", code: "OH" },
  { name: "Oklahoma", code: "OK" },
  { name: "Oregon", code: "OR" },
  { name: "Pennsylvania", code: "PA" },
  { name: "Rhode Island", code: "RI" },
  { name: "South Carolina", code: "SC" },
  { name: "South Dakota", code: "SD" },
  { name: "Tennessee", code: "TN" },
  { name: "Texas", code: "TX" },
  { name: "Utah", code: "UT" },
  { name: "Vermont", code: "VT" },
  { name: "Virginia", code: "VA" },
  { name: "Washington", code: "WA" },
  { name: "West Virginia", code: "WV" },
  { name: "Wisconsin", code: "WI" },
  { name: "Wyoming", code: "WY" }
];

export const companySizes = [
  "1-10 employees",
  "11-50 employees", 
  "51-100 employees",
  "101-500 employees",
  "501-1000 employees",
  "1000+ employees"
];

export const focusAreas = [
  "Industrial Construction",
  "Commercial Construction", 
  "Residential Construction",
  "Infrastructure Projects",
  "Energy & Utilities",
  "Manufacturing",
  "Marine & Offshore",
  "Mining & Resources",
  "Transportation",
  "Government Contracts"
];